version: '3.1'
services:
    centrifugo:
      container_name: centrifugo
      image: centrifugo/centrifugo
      restart: always
      ports:
        - 8000:8000
      ulimits:
        nofile:
            soft: 65536
            hard: 65536
      volumes:
        - ./.data:/centrifugo